# Generated by Django 5.2.17 on 2026-09-29 08:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True, max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(max_length=4000)),
                ('diagnosis', models.TextField(blank=True, max_length=8000)),
                ('fault_codes', models.CharField(blank=True, max_length=1000)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('received', 'Прийнято'), ('diagnosis', 'Діагностика'), ('approval', 'Очікує погодження'), ('parts', 'Очікує запчастин'), ('repair', 'У ремонті'), ('ready', 'Готово'), ('delivered', 'Видано')], db_index=True, default='received', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'Створення'), ('status', 'Статус'), ('comment', 'Коментар')], max_length=16)),
                ('text', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workshop.order')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('labor', 'Робота'), ('part', 'Запчастина')], max_length=8)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workshop.order')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('Model S', 'Model S'), ('Model 3', 'Model 3'), ('Model X', 'Model X'), ('Model Y', 'Model Y'), ('Cybertruck', 'Cybertruck'), ('Roadster', 'Roadster')], max_length=20)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2008), django.core.validators.MaxValueValidator(2100)])),
                ('vin', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator('^[A-HJ-NPR-Z0-9]{17}$', 'VIN має містити 17 латинських літер або цифр, без I, O, Q.')])),
                ('plate', models.CharField(blank=True, max_length=20)),
                ('mileage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3000000)])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='workshop.customer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='workshop.vehicle'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'due_date'], name='workshop_or_status_a1e265_idx'),
        ),
    ]
